<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'NITSAN\\NsLicense\\Controller\\NsLicenseModuleController' => $typo3InstallDir . 'typo3conf/ext/ns_license/Classes/Controller/NsLicenseModuleController.php',
    'NITSAN\\NsLicense\\Domain\\Repository\\NsLicenseRepository' => $typo3InstallDir . 'typo3conf/ext/ns_license/Classes/Domain/Repository/NsLicenseRepository.php',
    'NITSAN\\NsLicense\\Hooks\\BackendUserLogin' => $typo3InstallDir . 'typo3conf/ext/ns_license/Classes/Hooks/BackendUserLogin.php',
    'NITSAN\\NsLicense\\Setup' => $typo3InstallDir . 'typo3conf/ext/ns_license/Classes/Setup.php',
);
